dist: trusty
language: c
compiler:
  - gcc
script: make
python:
  - "3.4"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq ctags bison flex
  - sudo apt-get install -qq python3-pip python3-dev
  - sudo apt-get install -qq libtokyocabinet-dev libbz2-dev libz-dev
install:
  - sudo pip3 install jieba
